---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing
Edited the final version

## Introduction
### Literature research
Contributed to the references and formatting
### Writing

### Editing
Edited the final version

## Methods
### Writing
Worte the whole section 
### Editing
Edited the final version and made corrections based on feedback recieved for the project

## Results
### Analysis 
Analyzed the data and interpreted the results 
### Figures
+ Wrote the code to answer the second question regarding the significance of the abundance change with depth and oxygen concentration.  
+ Employed the linear regression model for the statistical analysis in R.
+ Troubleshot code for multiple figures.  
+ Explained code to teammates and added comments above code to clarify purpose.   
### Writing
Contributed to Figure legends  
### Editing
Edited the whole section and made corrections based on feedback recieved for the project

## Discussion
### Literature research
Contributed to references and formatting
### Writing

### Editing
Edited the whole section
