---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing
Wrote the whole abstract

### Editing
Edited section based on feedback 

## Introduction
### Literature research
Contributed to references and formatting
### Writing
Added the nitrogen cycle figure and expanded on the explanation of denitrification cycle 
### Editing
Edited entire section for final version and organized citations


## Methods
### Writing  
Wrote the entire section.

### Editing
Edited the final version 

## Results
### Anaysis 
Wrote part of the script for TreeSAPP. Troubleshot code in R to generate figures 2-5 and analyzed the final plots.  
### Figures
Interpreted results for all the plots, helped generate phylogenetic trees and orienting iTOL. 
### Writing
Wrote Figure 1 and 2 legends
### Editing
Edited the whole section 

## Discussion
### Literature research
Contributed to references and formatting
### Writing
 
### Editing
Edited the whole section and organized figure numbers.
